[package]
authors = ["chegde <chegde@outlook.com>"]
default-run = "chegde-v"
edition = "2018"
name = "chegde-v"
version = "0.0.1"

[dependencies]
actix-cors = "0.5.4"
actix-rt = "2"
actix-web = "3"

chrono = "0.4"
diesel = {version = "1.4", features = ["postgres"]}
dotenv = "0.15.0"

serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

bytes = "*"
futures = {version = "0.3.5"}

[dependencies.mongodb]
default-features = false
features = ["async-std-runtime"]
version = "1.0.0"
